import type { Club } from '$lib/types/game';

export const ALL_CLUBS: Club[] = [
	{ name: 'Arsenul', division: 1 },
	{ name: 'Viller', division: 1 },
	{ name: 'Bornmuth', division: 1 },
	{ name: 'Brentfurd', division: 1 },
	{ name: 'Bryton', division: 1 },
	{ name: 'Chelsee', division: 1 },
	{ name: 'Coventry', division: 1 },
	{ name: 'Pallace', division: 1 },
	{ name: 'Evarton', division: 1 },
	{ name: 'Fullum', division: 1 },
	{ name: 'Hull', division: 1 },
	{ name: 'Ipswitch', division: 1 },
	{ name: 'Leeds', division: 1 },
	{ name: 'Liverpoool', division: 1 },
	{ name: 'Man Citeh', division: 1 },
	{ name: 'Man Untied', division: 1 },
	{ name: 'Newcassel', division: 1 },
	{ name: 'Forrist', division: 1 },
	{ name: 'Sunderlun', division: 1 },
	{ name: 'Spurs', division: 1 },
	{ name: 'Birmingum', division: 2 },
	{ name: 'Blackbirn', division: 2 },
	{ name: 'Boltun', division: 2 },
	{ name: 'Bristol City', division: 2 },
	{ name: 'Burnlee', division: 2 },
	{ name: 'Cardif', division: 2 },
	{ name: 'Charltun', division: 2 },
	{ name: 'Darbee', division: 2 },
	{ name: 'Linkun', division: 2 },
	{ name: 'Boro', division: 2 },
	{ name: 'Millwol', division: 2 },
	{ name: 'Norrich', division: 2 },
	{ name: 'Pompee', division: 2 },
	{ name: 'Prestun', division: 2 },
	{ name: 'Cue Pee Arr', division: 2 },
	{ name: 'Sheff Yoonited', division: 2 },
	{ name: 'Saynts', division: 2 },
	{ name: 'Stoak', division: 2 },
	{ name: 'Swanzee', division: 2 },
	{ name: 'Wattfud', division: 2 },
	{ name: 'West Brom', division: 2 },
	{ name: 'West Ham', division: 2 },
	{ name: 'Woolvz', division: 2 },
	{ name: 'Rexham', division: 2 },
	{ name: 'Wimbledon', division: 3 },
	{ name: 'Barnslee', division: 3 },
	{ name: 'Blackpool', division: 3 },
	{ name: 'Bradfud', division: 3 },
	{ name: 'Bromlee', division: 3 },
	{ name: 'Burtun', division: 3 },
	{ name: 'Caimbridge', division: 3 },
	{ name: 'Doncaster', division: 3 },
	{ name: 'Huddersfeeld', division: 3 },
	{ name: 'Lestur', division: 3 },
	{ name: 'Orient', division: 3 },
	{ name: 'Looton', division: 3 },
	{ name: 'Mansfeeld', division: 3 },
	{ name: 'Em Kay Dons', division: 3 },
	{ name: 'Notts County', division: 3 },
	{ name: 'Oxfud', division: 3 },
	{ name: 'Peterbura', division: 3 },
	{ name: 'Plimuth', division: 3 },
	{ name: 'Redding', division: 3 },
	{ name: 'Sheff Wensday', division: 3 },
	{ name: 'Stevenij', division: 3 },
	{ name: 'Stockport', division: 3 },
	{ name: 'Wiggun', division: 3 },
	{ name: 'Wickham', division: 3 },
	{ name: 'Ackrington', division: 4 },
	{ name: 'Barnett', division: 4 },
	{ name: 'Bristol Rovers', division: 4 },
	{ name: 'Cheltnum', division: 4 },
	{ name: 'Chesterfeeld', division: 4 },
	{ name: 'Colchestur', division: 4 },
	{ name: 'Crawlee', division: 4 },
	{ name: 'Croo', division: 4 },
	{ name: 'Exetur', division: 4 },
	{ name: 'Fleetwud', division: 4 },
	{ name: 'Gillingham', division: 4 },
	{ name: 'Grimzbee', division: 4 },
	{ name: 'Newport', division: 4 },
	{ name: 'Northamptun', division: 4 },
	{ name: 'Oldum', division: 4 },
	{ name: 'Port Vayle', division: 4 },
	{ name: 'Rochdayle', division: 4 },
	{ name: 'Rotherum', division: 4 },
	{ name: 'Salfud', division: 4 },
	{ name: 'Shroosbury', division: 4 },
	{ name: 'Swindun', division: 4 },
	{ name: 'Tranmere', division: 4 },
	{ name: 'Walsawl', division: 4 },
	{ name: 'York', division: 4 }
];

export function getClubsByDivision(division: number): Club[] {
	return ALL_CLUBS.filter((c) => c.division === division);
}

export function getClub(name: string): Club | undefined {
	return ALL_CLUBS.find((c) => c.name === name);
}
